name: girman_technologies
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.4.3
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1

# flutter_launcher_icons:
#   android: true
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/fonts/poppins/
