// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsDyH0me0DfvO6NztMkaX-zAUfz_wrCro',
    appId: '1:842905157862:web:2c5692ee09219e0f917b27',
    messagingSenderId: '842905157862',
    projectId: 'griman-technologies-b5052',
    authDomain: 'griman-technologies-b5052.firebaseapp.com',
    storageBucket: 'griman-technologies-b5052.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi1kg65Nc25whvDZXdJxWzyaBO4IUfyik',
    appId: '1:842905157862:android:c0633a5843b1bff7917b27',
    messagingSenderId: '842905157862',
    projectId: 'griman-technologies-b5052',
    storageBucket: 'griman-technologies-b5052.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI29itTO7YdZizL4TTMAnDSRubUlHk1ZI',
    appId: '1:842905157862:ios:c57fb2308dba4bf8917b27',
    messagingSenderId: '842905157862',
    projectId: 'griman-technologies-b5052',
    storageBucket: 'griman-technologies-b5052.appspot.com',
    iosBundleId: 'com.example.girmanTechnologies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQgL3FmckYw3zNNe1aaeHKXvYwWwKHJYM',
    appId: '1:1080684299254:ios:2746784a4bb32a2c147dd7',
    messagingSenderId: '1080684299254',
    projectId: 'griman-technologies',
    storageBucket: 'griman-technologies.appspot.com',
    iosBundleId: 'com.example.girmanTechnologies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsFkE1qX5fq_tcR6N3m2C7BPqcwHnCUww',
    appId: '1:1080684299254:web:828005395d40e5f7147dd7',
    messagingSenderId: '1080684299254',
    projectId: 'griman-technologies',
    authDomain: 'griman-technologies.firebaseapp.com',
    storageBucket: 'griman-technologies.appspot.com',
  );
}